language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t eliasabay/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true eliasabay/react-test npm test

after_successs:
  - docker build -t eliasabay/multi-client ./client
  - docker build -t eliasabay/multi-nginx ./nginx
  - docker build -t eliasabay/multi-server ./server
  - docker build -t eliasabay/multi-worker ./worker