language: generic 
services:
  - docker

before_install:
  - docker build -t eliasabay/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true eliasabay/react-test npm test

after_success:
  - docker build -t eliasabay/multi-client ./client
  - docker build -t eliasabay/multi-nginx ./nginx
  - docker build -t eliasabay/multi-server ./server
  - docker build -t eliasabay/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_ID --password-stdin docker.io
  - docker push eliasabay/multi-client:latest
  - docker push eliasabay/multi-nginx:latest
  - docker push eliasabay/multi-server:latest
  - docker push eliasabay/multi-worker:latest